name: Docker mit AZ-Bordmitteln deployen
on:
    workflow_dispatch:

env:
  imageName: "track-dev-ops"
  containerName: "azure-container-test"
  resourceGroupName: "trackdev-Exp03"
  locationName: "germanywestcentral"
  tagName: "v0.0.14"
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: 'Azure authentication'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.containerName }}
        images: ${{ secrets.ACR_ENDPOINT }}/${{ env.imageName }}:${{ env.tagName }}
 
    - name: Azure logout
      run: |
        az logout
