name: Docker mit AZ-Bordmitteln deployen
on: [push]

env:
  imageName: "track-dev-ops"
  containerName: "azure-container-test"
  resourceGroupName: "trackdev-Exp03"
  locationName: "germanywestcentral"
  tagName: "v0-7"
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: 'Checkout Github-Repo'
      uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v5.3.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
        go-version: 1.22        
    - name: Install dependencies
      run: |
        cd ./azureContainerTest
        go get .          
    - name: Build Go Project
      run: |
        cd ./azureContainerTest
        go build -v ./...
             
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
 
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./azureContainerTest/Dockerfile
        build-args: |
            version=${{ steps.tag.outputs.tag }}
            tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.imageName }}:${{ env.tagName }}

    - name: 'Azure authentication'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WebApp_Name }}
        images: ${{ secrets.ACR_ENDPOINT }}/nodejsapp:${{ github.sha }}
 
    - name: Azure logout
      run: |
        az logout
